### ISSUE TITLE
Modelling myelinated axon (Question)

### ISSUE THREAD

**Issue by subash774** [neuronsimulator/pythontutorial#5]
Hi @ramcdougal ,
Thanks for a great tutorial, really helped me a lot!

I'm a master's student in Computer Science. My project is to model a HH cell (nodes of Ranvier) with myelinated axon and observe the effects of length of the myelinated axon. 

As I am completely new to neuroscience, I'm having some problems understanding the mechanisms of ```extracellular```. If I want a myelinated axon with the following paramters, how would I set this up in Python using NEURON? 

```
Params : {
    Myelin resistance (R_m): MOhms/mm
    Myelin capacitance: F/mm
    longitudinal resistance: MOhms/mm
    resting potential
}
```

Your help would be greatly appreciated. Thanks in advance!

**Comment by ramcdougal** [comment]
Thank you so much.

You should talk to Nooshin Abdollahi. Her poster (P168) looked at modeling the axon including the myelin with NEURON.

One of my colleagues here is more familiar with using the `extracellular` mechanism, and can give you a better answer, so I'm going to defer to him, besides to caution you that those are not NEURON's default units.

By the way, in the future, consider asking questions like this on the [NEURON forum](https://www.neuron.yale.edu/phpBB/).

**Comment by neuroman314** [comment]
Good question, subash774. Actually two questions in one (first is usage of extracellular, second is dealing with units). The NEURON Forum https://www.neuron.yale.edu/phpBB/ would be a perfect venue for this, since the answers will probably be seen by a wider audience. You seem not to be a Forum member, so I set up an account for you with the user name and email address that GitHub lists for you. I'll email the password to you; be sure to log in and change the pwd to something that only you will know. And then post your question in the Forum's "Getting started" discussion area.

**Comment by subash774** [comment]
@ramcdougal Thank you for the referral. Is there a way I can contact Nooshin Abdollahi? Would be very helpful if I could chat with her given my backgroud in Comp Sci and illiteracy in Neuroscience.

@neuroman314 Thanks a lot! I'll post the question there. 

Thank you both!
